### PR TITLE
General improvements

### PR DESCRIPTION
**Pull request by hectorfarahani**
Some General code improvements. More will come including replacing sidebar with meta boxes to let user show/hide them.
I got Your plugin link from reddit.

### CODE REVIEW

**Comment by lordspace** [comment]
Hey, thanks for making the improvements.
Let me review it and we will go from there.

Did you test it with php 5.6 (the minimal required WP version)?

**Comment by hectorfarahani** [comment]
Yes, Tested with PHP 5.6 and 7.4. Actually, I have tried to not drop support for PHP 5.6 y changing things.

**Comment by hectorfarahani** [comment]
Short description of what is changed:
1. Used functions instead of repeated code.
2. Used new function names based on WordPress convention. [Naming convention standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#naming-conventions)
3. Removed commented codes and unused codes.
4. Improved code readability. Tried to meet standards. (Done partially)

**Comment by lordspace** [comment]
Hi, can you please revert back all the do_action() and possibly apply_fitlers() calls so they are not in functions?
Also please make suggestions so things are discussed before done.

**Comment by hectorfarahani** [comment]
Hi, Sorry I had no time to work on this again. I may open some issues for improvements and I will send new PRs after discussion.

**Comment by lordspace** [comment]
ok. no problem. I will leave this as is then.
it's good to discuss first so the project stays on the minimalistic course.

**Pull request closed without merging**
